# Blog settings
permalink: /blog/:title


# My variables
name: Dabao Xiao
description: Android developer
google_verification: null


# File management
include: [".htaccess"]
exclude: [ "LICENSE"]


# Sass
sass:
  style: :compressed
  sass_dir: _sass


# Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge